import type { Metadata } from "next"
import { Nunito } from "next/font/google"

import "./globals.css"
import Providers from "@/lib/providers"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-nunito",
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "max-h-screen overflow-hidden  bg-background font-sans antialiased",
          nunito.variable
        )}
      >
        <ThemeProvider defaultTheme="light" attribute="class">
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
